apiVersion: 1

datasources:
  - name: Benchmark PostgreSQL
    type: postgres
    uid: benchmark-postgres
    url: postgres:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: benchmark
      sslmode: disable
      postgresVersion: 1300
      timescaledb: false
    editable: true
